### ISSUE TITLE
How to understand the gain score about 'No Answer Present' ?

### ISSUE THREAD

**Issue by jellying** [dfcf93/MSMARCOV2#1]
Hello, I can't understand the sentences in Readme as follow:
Given a query q and passages P, if the reference answer is 'No Answer Present' and the system produces and answer award a score of 0, If the reference answer is not 'No Answer Present' and the system produces the answer of 'No answer Present' award a score of 0. All other options gain a score of 1.
How to use the score in evaluation? Is there any examples?
And in the evaluation script 'ms_marco_eval.py' , I found it filter the no reference answer queries. Whether is the answer [''] equal to the answer ['No Answer Present']?

**Comment by dfcf93** [comment]
We will update the script soon to have a discounted score. Try 'No Answer Present.' instead of 'No Answer Present'

Basically for now until we release an updated please continue to use the evaluation scripts on our websites. Until we launch this we think ROUGE-L and BLEU will still capture systems how well systems perform on answers that aren't available.
